import type { Metadata } from "next";

import '@mantine/core/styles.css';

import { ColorSchemeScript, MantineProvider, mantineHtmlProps } from '@mantine/core';

import { JobModalProvider } from "@/context/JobModalContext";


export const metadata: Metadata = {
  title: "Job Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>

        <MantineProvider>
          <JobModalProvider>
            {children}
          </JobModalProvider>
        </MantineProvider>

      </body>
    </html>
  );
}
